# Generated by Django 5.0.1 on 2024-02-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_person_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
    ]
