# Generated by Django 5.0.2 on 2024-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_artist_name_alter_album_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop Music', 'Genre Pop Music'), ('Jazz Music', 'Genre Jazz Music'), ('Rock Music', 'Genre Rock Music'), ('Country Music', 'Genre Country Music'), ('R&B Music', 'Genre Rnb Music'), ('Dance Music', 'Genre Dance Music'), ('Hip Hop Music', 'Genre Hip Hop Music'), ('Other', 'Genre Other Music')], max_length=30),
        ),
    ]
