# Generated by Django 5.0.1 on 2024-01-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='car_brand',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='car_model',
            field=models.CharField(blank=True, null=True),
        ),
    ]
